Third week
Kalter-M/population pull request #4
Opened 2018-07-17 10:33 UTC by Kalter-M

2018-07-17 18:15 UTC, kgoncharov requested changes

2018-07-17 18:15 UTC, kgoncharov commented on docker/Dockerfile
> +ENTRYPOINT ["/usr/bin/mongod", "--bind_ip_all"]
Why do we need separate `Dockerfile` for MongoDb? Can we use some standard image from dockerhub instead?

2018-07-17 18:15 UTC, kgoncharov commented on src/main/scala/ru/dsr/bigdata/Jobs.scala
> +
No `vars`! Especially in objects. Keep it immutable and functional. 
Better to increase amount of args for function.

2018-07-17 18:15 UTC, kgoncharov commented on src/main/scala/ru/dsr/bigdata/Jobs.scala
> +  implicit class Runner(val job: () => Dataset[Row]) {
Try to avoid implicits in all similar cases. 
Make functions that take source datasets (or even load and save strategies) as parameters.

2018-07-17 19:26 UTC, Kalter-M commented on src/main/scala/ru/dsr/bigdata/Jobs.scala
> +  implicit class Runner(val job: () => Dataset[Row]) {
I just tried to make a structure like in the example from the past MR) 
Is it better to transfer to jobs load and save strategy like this?
```
 def getPopulation(loadStrategy: Loader, saveStrategy: Saver, name: String): Unit = {
    val result = loadStrategy.load(loadStrategy.both)
      .select(
...
    saveStrategy.save(result, name)
}
```
and in the launcher
```
case "population" =>
   getPopulation(loadStrategy, saveStrategy, AppConfig.job)
```

2018-07-17 19:29 UTC, Kalter-M commented on docker/Dockerfile
> +ENTRYPOINT ["/usr/bin/mongod", "--bind_ip_all"]
This is an attempt to make the docker working for Windows. Perhaps, now the standard image will work. I'll try it.

2018-07-24 18:07 UTC, kgoncharov approved these changes

2018-07-24 18:07 UTC, kgoncharov commented on shell/start.sh
> +docker run -d -p 27017:27017 mongo:3.6
Do we need `docker pull mongo:3.6` for the first launch? Please, add this to the script

2018-07-24 18:07 UTC, kgoncharov commented on shell/start.sh
> +export SPARK_HOME=/usr/local/spark
Paths can be different, remove this line and add comment. Something like "Env var SPARK_HOME should be set"

2018-07-25 11:04 UTC, merged